### ISSUE TITLE
contact form delete button not working

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Contacts#10]
This is  a **bug request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

contactform used modal and when click delete button second modal behind contact form so could not delete
### Steps to Reproduce

contacts->edit->delete button click
### Expected behavior

second delete modal open front of contactform modal

**Comment by aocneanu** [comment]
I don't think that we want to show two modals at once. The contact is still deletable from the main table, after closing the form.

For now I just removed the delete button from the contact edit form
