### ISSUE TITLE
Tag the latest release which contains test fixes

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/Contacts#11]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Last commit 4 days ago with test fixes. Last tag 5 days ago. Can you tag please?

### Steps to Reproduce
Travis build with/or PHP Unit with latest Enso

### Expected behavior
Pass tests

### Actual behavior
Failed on two tests

**Comment by aocneanu** [comment]
Done!

**Comment by curtisdelicata** [comment]
Thank you.


________________________________
