### ISSUE TITLE
created_by no migration

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Contacts#12]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Missing created_by migration in recent upgrade?
`Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 1 table contacts has no column named created_by (SQL: insert into "contacts" ("is_active", "contactable_id", "contactable_type", "first_name", "last_name", "phone", "email", "created_by", "updated_at", "created_at") values (1, 1, ContactTestModel, Luella, Boyle, 486.730.7529, jfay@example.org, 2, 2018-10-15 12:16:32, 2018-10-15 12:16:32))`

### Steps to Reproduce
1. Upgrade to latest Enso (still worked in 11.12.5)
2. Run tests

### Expected behavior

Tests to pass

### Actual behavior

Above error; indicating a migration to add `created_by` is likely missing

**Comment by aocneanu** [comment]
changelog

![image](https://user-images.githubusercontent.com/16073274/46945662-0a2d5580-d07e-11e8-89b0-120d24f1121b.png)

**Comment by jlsjonas** [comment]
Looks like my ContactFactory still had a created_by causing the issue; documentation misser? (I only experienced the issue after upgrading to 11.12.6)

I did notice the changelog before creating the issue 😅

**Comment by jlsjonas** [comment]
Going to reopen this as it couldn't be legacy code creating the issue; I didn't know about Enso at v.2.7.6.; I only started using it somewhere in August.

**Comment by jlsjonas** [comment]
Looks like https://github.com/laravel-enso/Contacts/commit/ed908ab3581b21a259ecb676053655119303029d#diff-33fb8b803a6de10c883f720a9c0f1291 added created_by but it was fixed 8 days ago.
